### ISSUE TITLE
QC.Rmd requires additional packages

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#55]
I ran the qc-1 pipeline which generates QC.Rmd
Attempted to render this file on the command line using
> Rscript -e "rmarkdown::render('QC.Rmd')"
Before this would work I had to install the following packages (using mamba)
> mamba install -c bioconda bioconductor-tximport
> mamba install -c bioconda bioconductor-busparse
> mamba install -c bioconda r-seurat
> mamba install -c bioconda/label/broken r-ggthemes

**Comment by Acribbs** [comment]
should already be in environment.yml see #88
