### ISSUE TITLE
Bug in QC.Rmd

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#56]
Line 158 
ensembl <- try(useMart("ensembl", dataset = "hsapiens_gene_ensembl", mirror=ini$mirror))
if(class(ensembl) == "try-error"){
  httr::set_config(httr::config(ssl_verifypeer = FALSE))
  ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
}

We need to remove the argument mirror=ini$mirror because this is not an argument for useMart and causes it to crash.

**Comment by carlacohen** [comment]
I have addressed this in commit eeadb14 on branch carla

**Comment by Acribbs** [comment]
want to make the pull request?

**Comment by Acribbs** [comment]
Think this can be closed @carlacohen ?

**Comment by carlacohen** [comment]
yes it can
