### ISSUE TITLE
QC.Rmd filtering error

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#57]
QC.Rmd line 229
Comments say remove cells with <100 UMIs but command says which(metadata$nUMI > 5), surely this should be which(metadata$nUMI > 100)? 

Also when we created the Seurat object, we used min.features = 200 so this step is not going to change anything.

**Comment by Acribbs** [comment]
Ah one issue with this is that the filter should probably be added to the min.features when making Seurat object because it reduces the vector size that is generated

**Comment by carlacohen** [comment]
OK I will move it to the min.features instead then do a new commit and pull request.
