### ISSUE TITLE
Filter.QC requires SeuratData installation

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#58]
FilterQC.Rmd is run during the filter-2 pipeline.
This requires the SeuratData package.
Installing with mamba did not work so I installed via github using R in the terminal 
> R
Load SeuratDisk via github
> if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
> remotes::install_github("mojaveazure/seurat-disk")

**Comment by Acribbs** [comment]
Thanks fixed with #88
