### ISSUE TITLE
Windows issue with fonts

### ISSUE THREAD

**Issue by carlacohen** [cribbslab/scflow#59]
The custom ggplot theme "theme_Publication" specifies base_family = "Arial". 
This gives an error in Windows saying "font family not found in Windows font database".
However it does not interrupt plotting of the graphs.

This error can be overcome by using the following packages:

> install.packages("extrafont")
> library(extrafont)
Need to install a specific version of one particular dependency.
> library(remotes)
> remotes::install_version("Rttf2pt1", version = "1.3.8")
> extrafont::font_import()
> loadfonts(device = "win")

See 
https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2
and
https://stackoverflow.com/questions/61204259/how-can-i-resolve-the-no-font-name-issue-when-importing-fonts-into-r-using-ext

**Comment by Acribbs** [comment]
We would never be running the pipelines on a windows system though. Probably dont need to support this.

**Comment by carlacohen** [comment]
Ah true, this is just because I was playing around with the script on my local machine to see what it is doing.
